permutation_task:
  description: >
    Use the permuatation tool for generating the permutations. Use ONLY the permutation_tool to complete this task. Do not delegate this to any other agent.
    
  expected_output: >
    The inputs have been given to you, give these inputs to tool user_data: {user_data}, num_permutations: {num_permutations}.    
  agent: permutation_agent
#   output_file: output/permuted_data1.json



query_task:
  description: >
    use 'query_tool'
  expected_output: >
    just run the tool
  agent: query_agent
#   output_file: output/queries.json

search_task:
  description: >
    use 'search_tool'
  expected_output: >
    just run the tool
  agent: search_agent


scraping_task:
  description: >
    use 'scraping_tool'
  expected_output: >
    just run the tool
  agent: scraping_agent

summarizer_task:
  description: >
    use 'scraping_tool'
  expected_output: >
    just run the tool
    
  agent: summarizer_agent
#    A JSON AML report with the following structure:
#    {
#      "topic": "<AML Topic>",
#      "total_permutations": <int>,
#      "total_queries": <int>,
#     "summary": "<Comprehensive summary>"
#    }
#    The report should be stored in output/aml_report.json.

#   agent: summarizer_agent

